import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | Dynamic title",
  },
  description: "Generated by Next.js",
  icons: "/globe.svg",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "20px" }}>
          <h1>Header</h1>
        </header>
        {children}
        <footer style={{ backgroundColor: "lightCyan", padding: "20px" }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
